services:
  package:
    image: ghcr.io/voidzero-dev/vite-plus:latest
    tty: true
    stdin_open: true
    working_dir: /app
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_API_KEY=masterKey
    depends_on:
      - meilisearch
    links:
      - meilisearch
    volumes:
      - ./:/app

  meilisearch:
    image: getmeili/meilisearch-enterprise:latest
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
      - MEILI_EXPERIMENTAL_ALLOWED_IP_NETWORKS=any
