name: Tests

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: check
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1.21.1
        with:
          node-version: "24"
          cache: true
      - run: vp install
      - name: Run format, lint, and types check
        run: vp check

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["22", "24"]
    name: tests (Node.js ${{ matrix.node-version }})
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1.21.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: true
      - run: vp install
      - name: Run unit tests
        run: vp test

  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v7
      - uses: voidzero-dev/setup-vp@v1.21.1
        with:
          node-version: "24"
          cache: true
      - run: vp install
      - name: Build package
        run: vp pack
